extends Node
## Central lookup for every UI-facing string. Never hardcode player-visible text in a scene script —
## add a key here (in every language table) and call Localization.get_string(key) instead.

signal language_changed(language_code: String)

var current_language: String = "en"

var _strings: Dictionary = {
	"en": {
		"common.connection_error": "Connection error, is the server running?",
		"common.continue": "Continue",
		"common.back": "Back",
		"common.cancel": "Cancel",
		"common.submit": "Submit",
		"common.loading": "Loading...",

		"menu.title": "CyberGuard 3D",
		"menu.login": "Login",
		"menu.register": "Register",
		"menu.leaderboard": "Leaderboard",
		"menu.quit": "Quit",
		"menu.language": "Language",
		"menu.logout": "Log Out",

		"login.title": "Login",
		"login.username": "Username",
		"login.password": "Password",
		"login.submit": "Login",
		"login.switch_to_register": "Need an account? Register",
		"login.error_generic": "Login failed.",

		"register.title": "Register",
		"register.username": "Username",
		"register.email": "Email",
		"register.password": "Password",
		"register.confirm_password": "Confirm Password",
		"register.submit": "Register",
		"register.switch_to_login": "Already have an account? Login",
		"register.error_password_mismatch": "Passwords do not match.",
		"register.error_empty_fields": "All fields are required.",
		"register.error_invalid_email": "Enter a valid email address.",
		"register.success": "Account created! Please log in.",

		"hud.trust_score": "Trust Score",
		"hud.room_label": "Room",

		"rooms.phishing_inbox": "Phishing Inbox",
		"rooms.upi_otp_kiosk": "UPI / OTP Kiosk",
		"rooms.fake_login_corridor": "Fake Login Corridor",
		"rooms.password_vault_lab": "Password Vault Lab",
		"rooms.safe_browsing_street": "Safe Browsing Street",
		"rooms.rapid_fire": "Rapid Fire",
		"rooms.vulnerability_hunt": "Vulnerability Hunt",

		"action.email.opened": "Open",
		"action.email.reported": "Report",
		"action.email.deleted": "Delete",
		"action.email.ignored": "Ignore",
		"action.payment.approve": "Approve",
		"action.payment.decline": "Decline",
		"action.payment.verify_first": "Verify First",
		"action.login.enter_credentials": "Enter Credentials",
		"action.login.check_url": "Check URL",
		"action.login.leave_page": "Leave Page",
		"action.storefront.enter_site": "Enter Site",
		"action.storefront.check_certificate": "Check Certificate",
		"action.storefront.leave": "Leave",

		"password.title": "Set Your Password",
		"password.placeholder": "Type a password...",
		"password.strength_weak": "Weak",
		"password.strength_medium": "Medium",
		"password.strength_strong": "Strong",
		"password.submit": "Submit Password",

		"debrief.correct": "Correct!",
		"debrief.incorrect": "That was a mistake.",
		"debrief.trust_change": "Trust Score",
		"debrief.red_flags_title": "What gave it away:",
		"debrief.none_title": "Why this was safe:",
		"debrief.continue": "Continue",

		"badge.toast_prefix": "Badge earned:",
		"badge.phishing_inbox_expert": "Phishing Expert",
		"badge.upi_otp_kiosk_expert": "UPI Safety Expert",
		"badge.fake_login_corridor_expert": "Login Vigilance Expert",
		"badge.password_vault_lab_expert": "Password Pro",
		"badge.safe_browsing_street_expert": "Safe Browsing Expert",

		"leaderboard.title": "Leaderboard",
		"leaderboard.rank": "Rank",
		"leaderboard.username": "Player",
		"leaderboard.trust_score": "Trust Score",
		"leaderboard.empty": "No scores yet. Be the first!",

		"admin.title": "CyberGuard 3D - Scenario Admin",
		"admin.add": "Add Scenario",
		"admin.edit": "Edit",
		"admin.delete": "Delete",
		"admin.save": "Save",
		"admin.cancel": "Cancel",
		"admin.field.code": "Code",
		"admin.field.room": "Room",
		"admin.field.title": "Title",
		"admin.field.difficulty": "Difficulty",
		"admin.field.is_fraud": "Is Fraud",
		"admin.field.red_flags": "Red Flags",
		"admin.field.correct_actions": "Correct Actions",
		"admin.no_auth_notice": "No admin authentication in this build phase - see README.",
		"admin.field.content": "Content (JSON)",

		"email.reader.tooltip_prefix": "Real address: ",
		"email.reader.instruction": "Read the email carefully. Hover over the sender or the link to inspect them.",

		"upi.otp_placeholder": "Enter the OTP you received",
		"upi.submit_otp": "Submit OTP",
		"upi.incoming_request": "Incoming Request",
		"upi.time_remaining": "Time remaining:",

		"login.zoom_domain": "Inspect Address Bar",
		"login.flag_suspicious": "Flag as Suspicious",
		"login.looks_legit": "Looks Legitimate",
		"login.zoom_instruction": "Tap the address bar to examine it closely before deciding.",

		"password.crack_time_label": "Time to crack:",
		"password.crack_instant": "Instantly",
		"password.crack_centuries": "centuries",
		"password.crack_status_cracked": "CRACKED!",
		"password.crack_status_secure": "SECURE",
		"password.unit_seconds": "seconds",
		"password.unit_minutes": "minutes",
		"password.unit_hours": "hours",
		"password.unit_days": "days",
		"password.unit_years": "years",

		"storefront.claim_now": "Claim Now!",
		"storefront.address_prefix": "Address: ",

		"level.1": "Cyber Rookie",
		"level.2": "Digital Scout",
		"level.3": "Threat Spotter",
		"level.4": "Cyber Trainee",
		"level.5": "Security Agent",
		"level.6": "Cyber Investigator",
		"level.7": "Threat Analyst",
		"level.8": "Cyber Defender",
		"level.9": "Elite Defender",
		"level.10": "Cyber Sentinel",

		"streak.combo_prefix": "Combo",
		"streak.level_up_prefix": "LEVEL UP!",

		"debrief.score_base": "Base",
		"debrief.score_speed_bonus": "Speed Bonus",
		"debrief.score_streak_bonus": "Streak Bonus",

		"badge.perfect_run": "Perfect Run",
		"badge.speed_demon": "Speed Demon",
		"badge.cyber_sentinel": "Cyber Sentinel",

		"action.rapidfire.safe": "Safe",
		"action.rapidfire.unsafe": "Unsafe",
		"rapidfire.instruction": "Decide fast - SAFE or UNSAFE?",
		"rapidfire.timeout": "Time's up!",

		"action.vulnhunt.flag": "Flag as Vulnerability",
		"action.vulnhunt.ignore": "This Is Fine",

		"menu.cybersense": "CyberSense",
		"cybersense.title": "CyberSense",
		"cybersense.subtitle": "Paste a suspicious message and get an instant risk analysis.",
		"cybersense.placeholder": "Paste an email, message, or call transcript here...",
		"cybersense.analyze": "Analyze",
		"cybersense.risk_label": "Risk Level:",
		"cybersense.risk_low": "LOW RISK",
		"cybersense.risk_medium": "MEDIUM RISK",
		"cybersense.risk_high": "HIGH RISK",
		"cybersense.risk_critical": "CRITICAL RISK",
		"cybersense.indicators_title": "Indicators Found:",
		"cybersense.no_indicators": "No obvious red flags detected - but always stay cautious.",
		"cybersense.empty_input": "Paste some text first.",
		"cybersense.indicator_urgency": "Urgency language pressuring you to act fast",
		"cybersense.indicator_credential_request": "Requests a credential (OTP, PIN, password, or CVV)",
		"cybersense.indicator_suspicious_link": "Contains a suspicious or shortened link",
		"cybersense.indicator_generic_greeting": "Generic greeting instead of your real name",
		"cybersense.indicator_too_good": "Too-good-to-be-true prize or cashback offer",
		"cybersense.indicator_payment_pressure": "Pressures you to send or approve a payment",
	},
	"hi": {
		"common.connection_error": "कनेक्शन त्रुटि, क्या सर्वर चल रहा है?",
		"common.continue": "जारी रखें",
		"common.back": "वापस",
		"common.cancel": "रद्द करें",
		"common.submit": "जमा करें",
		"common.loading": "लोड हो रहा है...",

		"menu.title": "साइबरगार्ड 3D",
		"menu.login": "लॉगिन",
		"menu.register": "रजिस्टर करें",
		"menu.leaderboard": "लीडरबोर्ड",
		"menu.quit": "बाहर निकलें",
		"menu.language": "भाषा",
		"menu.logout": "लॉग आउट",

		"login.title": "लॉगिन",
		"login.username": "उपयोगकर्ता नाम",
		"login.password": "पासवर्ड",
		"login.submit": "लॉगिन करें",
		"login.switch_to_register": "खाता नहीं है? रजिस्टर करें",
		"login.error_generic": "लॉगिन विफल।",

		"register.title": "रजिस्टर करें",
		"register.username": "उपयोगकर्ता नाम",
		"register.email": "ईमेल",
		"register.password": "पासवर्ड",
		"register.confirm_password": "पासवर्ड की पुष्टि करें",
		"register.submit": "रजिस्टर करें",
		"register.switch_to_login": "पहले से खाता है? लॉगिन करें",
		"register.error_password_mismatch": "पासवर्ड मेल नहीं खाते।",
		"register.error_empty_fields": "सभी फ़ील्ड आवश्यक हैं।",
		"register.error_invalid_email": "मान्य ईमेल पता दर्ज करें।",
		"register.success": "खाता बन गया! कृपया लॉगिन करें।",

		"hud.trust_score": "ट्रस्ट स्कोर",
		"hud.room_label": "कमरा",

		"rooms.phishing_inbox": "फ़िशिंग इनबॉक्स",
		"rooms.upi_otp_kiosk": "यूपीआई / ओटीपी कियोस्क",
		"rooms.fake_login_corridor": "नकली लॉगिन गलियारा",
		"rooms.password_vault_lab": "पासवर्ड वॉल्ट लैब",
		"rooms.safe_browsing_street": "सुरक्षित ब्राउज़िंग स्ट्रीट",
		"rooms.rapid_fire": "रैपिड फायर",
		"rooms.vulnerability_hunt": "वल्नरेबिलिटी हंट",

		"action.email.opened": "खोलें",
		"action.email.reported": "रिपोर्ट करें",
		"action.email.deleted": "हटाएं",
		"action.email.ignored": "अनदेखा करें",
		"action.payment.approve": "स्वीकृत करें",
		"action.payment.decline": "अस्वीकार करें",
		"action.payment.verify_first": "पहले सत्यापित करें",
		"action.login.enter_credentials": "क्रेडेंशियल दर्ज करें",
		"action.login.check_url": "यूआरएल जांचें",
		"action.login.leave_page": "पेज छोड़ें",
		"action.storefront.enter_site": "साइट में प्रवेश करें",
		"action.storefront.check_certificate": "प्रमाणपत्र जांचें",
		"action.storefront.leave": "छोड़ें",

		"password.title": "अपना पासवर्ड सेट करें",
		"password.placeholder": "एक पासवर्ड टाइप करें...",
		"password.strength_weak": "कमज़ोर",
		"password.strength_medium": "मध्यम",
		"password.strength_strong": "मज़बूत",
		"password.submit": "पासवर्ड जमा करें",

		"debrief.correct": "सही!",
		"debrief.incorrect": "यह एक गलती थी।",
		"debrief.trust_change": "ट्रस्ट स्कोर",
		"debrief.red_flags_title": "इससे पता चला:",
		"debrief.none_title": "यह सुरक्षित क्यों था:",
		"debrief.continue": "जारी रखें",

		"badge.toast_prefix": "बैज अर्जित:",
		"badge.phishing_inbox_expert": "फ़िशिंग विशेषज्ञ",
		"badge.upi_otp_kiosk_expert": "यूपीआई सुरक्षा विशेषज्ञ",
		"badge.fake_login_corridor_expert": "लॉगिन सतर्कता विशेषज्ञ",
		"badge.password_vault_lab_expert": "पासवर्ड प्रो",
		"badge.safe_browsing_street_expert": "सुरक्षित ब्राउज़िंग विशेषज्ञ",

		"leaderboard.title": "लीडरबोर्ड",
		"leaderboard.rank": "रैंक",
		"leaderboard.username": "खिलाड़ी",
		"leaderboard.trust_score": "ट्रस्ट स्कोर",
		"leaderboard.empty": "अभी तक कोई स्कोर नहीं। पहले बनें!",

		"admin.title": "साइबरगार्ड 3D - परिदृश्य व्यवस्थापक",
		"admin.add": "परिदृश्य जोड़ें",
		"admin.edit": "संपादित करें",
		"admin.delete": "हटाएं",
		"admin.save": "सहेजें",
		"admin.cancel": "रद्द करें",
		"admin.field.code": "कोड",
		"admin.field.room": "कमरा",
		"admin.field.title": "शीर्षक",
		"admin.field.difficulty": "कठिनाई",
		"admin.field.is_fraud": "क्या धोखाधड़ी है",
		"admin.field.red_flags": "चेतावनी संकेत",
		"admin.field.correct_actions": "सही कार्रवाई",
		"admin.no_auth_notice": "इस निर्माण चरण में कोई व्यवस्थापक प्रमाणीकरण नहीं है - README देखें।",
		"admin.field.content": "सामग्री (JSON)",

		"email.reader.tooltip_prefix": "असली पता: ",
		"email.reader.instruction": "ईमेल ध्यान से पढ़ें। प्रेषक या लिंक की जांच करने के लिए उस पर होवर करें।",

		"upi.otp_placeholder": "प्राप्त ओटीपी दर्ज करें",
		"upi.submit_otp": "ओटीपी जमा करें",
		"upi.incoming_request": "इनकमिंग रिक्वेस्ट",
		"upi.time_remaining": "शेष समय:",

		"login.zoom_domain": "एड्रेस बार जांचें",
		"login.flag_suspicious": "संदिग्ध के रूप में चिह्नित करें",
		"login.looks_legit": "वैध लगता है",
		"login.zoom_instruction": "निर्णय लेने से पहले एड्रेस बार को ध्यान से जांचने के लिए उस पर टैप करें।",

		"password.crack_time_label": "क्रैक होने में समय:",
		"password.crack_instant": "तुरंत",
		"password.crack_centuries": "सदियाँ",
		"password.crack_status_cracked": "क्रैक हो गया!",
		"password.crack_status_secure": "सुरक्षित",
		"password.unit_seconds": "सेकंड",
		"password.unit_minutes": "मिनट",
		"password.unit_hours": "घंटे",
		"password.unit_days": "दिन",
		"password.unit_years": "वर्ष",

		"storefront.claim_now": "अभी क्लेम करें!",
		"storefront.address_prefix": "पता: ",

		"level.1": "साइबर रूकी",
		"level.2": "डिजिटल स्काउट",
		"level.3": "थ्रेट स्पॉटर",
		"level.4": "साइबर ट्रेनी",
		"level.5": "सिक्योरिटी एजेंट",
		"level.6": "साइबर इन्वेस्टिगेटर",
		"level.7": "थ्रेट एनालिस्ट",
		"level.8": "साइबर डिफेंडर",
		"level.9": "एलीट डिफेंडर",
		"level.10": "साइबर सेंटिनल",

		"streak.combo_prefix": "कॉम्बो",
		"streak.level_up_prefix": "लेवल अप!",

		"debrief.score_base": "आधार",
		"debrief.score_speed_bonus": "स्पीड बोनस",
		"debrief.score_streak_bonus": "स्ट्रीक बोनस",

		"badge.perfect_run": "परफेक्ट रन",
		"badge.speed_demon": "स्पीड डेमन",
		"badge.cyber_sentinel": "साइबर सेंटिनल",

		"action.rapidfire.safe": "सुरक्षित",
		"action.rapidfire.unsafe": "असुरक्षित",
		"rapidfire.instruction": "जल्दी तय करें - सुरक्षित या असुरक्षित?",
		"rapidfire.timeout": "समय समाप्त!",

		"action.vulnhunt.flag": "कमजोरी के रूप में चिह्नित करें",
		"action.vulnhunt.ignore": "यह ठीक है",

		"menu.cybersense": "साइबरसेंस",
		"cybersense.title": "साइबरसेंस",
		"cybersense.subtitle": "एक संदिग्ध संदेश पेस्ट करें और तुरंत जोखिम विश्लेषण प्राप्त करें।",
		"cybersense.placeholder": "यहां एक ईमेल, संदेश, या कॉल ट्रांसक्रिप्ट पेस्ट करें...",
		"cybersense.analyze": "विश्लेषण करें",
		"cybersense.risk_label": "जोखिम स्तर:",
		"cybersense.risk_low": "कम जोखिम",
		"cybersense.risk_medium": "मध्यम जोखिम",
		"cybersense.risk_high": "उच्च जोखिम",
		"cybersense.risk_critical": "गंभीर जोखिम",
		"cybersense.indicators_title": "पाए गए संकेतक:",
		"cybersense.no_indicators": "कोई स्पष्ट चेतावनी संकेत नहीं मिला - फिर भी सतर्क रहें।",
		"cybersense.empty_input": "पहले कुछ टेक्स्ट पेस्ट करें।",
		"cybersense.indicator_urgency": "जल्दबाजी में कार्रवाई करने का दबाव डालने वाली भाषा",
		"cybersense.indicator_credential_request": "क्रेडेंशियल (OTP, PIN, पासवर्ड, या CVV) मांगता है",
		"cybersense.indicator_suspicious_link": "एक संदिग्ध या छोटा किया गया लिंक शामिल है",
		"cybersense.indicator_generic_greeting": "आपके असली नाम के बजाय सामान्य अभिवादन",
		"cybersense.indicator_too_good": "बहुत अच्छा लगने वाला इनाम या कैशबैक ऑफर",
		"cybersense.indicator_payment_pressure": "भुगतान भेजने या स्वीकृत करने का दबाव डालता है",
	},
}


func set_language(code: String) -> void:
	if not _strings.has(code):
		code = "en"
	current_language = code
	language_changed.emit(code)


func get_string(key: String) -> String:
	var table: Dictionary = _strings.get(current_language, _strings["en"])
	if table.has(key):
		return table[key]
	return _strings["en"].get(key, key)


func available_languages() -> Array:
	return _strings.keys()
