extends Node
## Central lookup for every UI-facing string. Never hardcode player-visible text in a scene script —
## add a key here (in every language table) and call Localization.get_string(key) instead.

signal language_changed(language_code: String)

var current_language: String = "en"

var _strings: Dictionary = {
	"en": {
		"common.connection_error": "Connection error, is the server running?",
		"common.continue": "Continue",
		"common.back": "Back",
		"common.cancel": "Cancel",
		"common.submit": "Submit",
		"common.loading": "Loading...",

		"menu.title": "CyberGuard 3D",
		"menu.login": "Login",
		"menu.register": "Register",
		"menu.leaderboard": "Leaderboard",
		"menu.quit": "Quit",
		"menu.language": "Language",
		"menu.logout": "Log Out",

		"login.title": "Login",
		"login.username": "Username",
		"login.password": "Password",
		"login.submit": "Login",
		"login.switch_to_register": "Need an account? Register",
		"login.error_generic": "Login failed.",

		"register.title": "Register",
		"register.username": "Username",
		"register.email": "Email",
		"register.password": "Password",
		"register.confirm_password": "Confirm Password",
		"register.submit": "Register",
		"register.switch_to_login": "Already have an account? Login",
		"register.error_password_mismatch": "Passwords do not match.",
		"register.error_empty_fields": "All fields are required.",
		"register.error_invalid_email": "Enter a valid email address.",
		"register.success": "Account created! Please log in.",

		"hud.trust_score": "Trust Score",
		"hud.room_label": "Room",

		"rooms.phishing_inbox": "Phishing Inbox",
		"rooms.upi_otp_kiosk": "UPI / OTP Kiosk",
		"rooms.fake_login_corridor": "Fake Login Corridor",
		"rooms.password_vault_lab": "Password Vault Lab",
		"rooms.safe_browsing_street": "Safe Browsing Street",
		"rooms.rapid_fire": "Rapid Fire",
		"rooms.vulnerability_hunt": "Vulnerability Hunt",
		"rooms.cybersense": "CyberSense",

		"action.email.opened": "Open",
		"action.email.reported": "Report",
		"action.email.deleted": "Delete",
		"action.email.ignored": "Ignore",
		"action.payment.approve": "Approve",
		"action.payment.decline": "Decline",
		"action.payment.verify_first": "Verify First",
		"action.login.enter_credentials": "Enter Credentials",
		"action.login.check_url": "Check URL",
		"action.login.leave_page": "Leave Page",
		"action.storefront.enter_site": "Enter Site",
		"action.storefront.check_certificate": "Check Certificate",
		"action.storefront.leave": "Leave",

		"password.title": "Set Your Password",
		"password.placeholder": "Type a password...",
		"password.strength_weak": "Weak",
		"password.strength_medium": "Medium",
		"password.strength_strong": "Strong",
		"password.submit": "Submit Password",

		"debrief.correct": "Correct!",
		"debrief.incorrect": "That was a mistake.",
		"debrief.trust_change": "Trust Score",
		"debrief.red_flags_title": "What gave it away:",
		"debrief.none_title": "Why this was safe:",
		"debrief.continue": "Continue",

		"badge.toast_prefix": "Badge earned:",
		"badge.phishing_inbox_expert": "Phishing Expert",
		"badge.upi_otp_kiosk_expert": "UPI Safety Expert",
		"badge.fake_login_corridor_expert": "Login Vigilance Expert",
		"badge.password_vault_lab_expert": "Password Pro",
		"badge.safe_browsing_street_expert": "Safe Browsing Expert",

		"leaderboard.title": "Leaderboard",
		"leaderboard.rank": "Rank",
		"leaderboard.username": "Player",
		"leaderboard.trust_score": "Trust Score",
		"leaderboard.empty": "No scores yet. Be the first!",

		"admin.title": "CyberGuard 3D - Scenario Admin",
		"admin.add": "Add Scenario",
		"admin.edit": "Edit",
		"admin.delete": "Delete",
		"admin.save": "Save",
		"admin.cancel": "Cancel",
		"admin.field.code": "Code",
		"admin.field.room": "Room",
		"admin.field.title": "Title",
		"admin.field.difficulty": "Difficulty",
		"admin.field.is_fraud": "Is Fraud",
		"admin.field.red_flags": "Red Flags",
		"admin.field.correct_actions": "Correct Actions",
		"admin.no_auth_notice": "No admin authentication in this build phase - see README.",
		"admin.field.content": "Content (JSON)",

		"email.reader.tooltip_prefix": "Real address: ",
		"email.reader.instruction": "Read the email carefully. Hover over the sender or the link to inspect them.",

		"upi.otp_placeholder": "Enter the OTP you received",
		"upi.submit_otp": "Submit OTP",
		"upi.incoming_request": "Incoming Request",
		"upi.time_remaining": "Time remaining:",

		"login.zoom_domain": "Inspect Address Bar",
		"login.flag_suspicious": "Flag as Suspicious",
		"login.looks_legit": "Looks Legitimate",
		"login.zoom_instruction": "Tap the address bar to examine it closely before deciding.",

		"password.crack_time_label": "Time to crack:",
		"password.crack_instant": "Instantly",
		"password.crack_centuries": "centuries",
		"password.crack_status_cracked": "CRACKED!",
		"password.crack_status_secure": "SECURE",
		"password.unit_seconds": "seconds",
		"password.unit_minutes": "minutes",
		"password.unit_hours": "hours",
		"password.unit_days": "days",
		"password.unit_years": "years",

		"storefront.claim_now": "Claim Now!",
		"storefront.address_prefix": "Address: ",

		"level.1": "Cyber Rookie",
		"level.2": "Digital Scout",
		"level.3": "Threat Spotter",
		"level.4": "Cyber Trainee",
		"level.5": "Security Agent",
		"level.6": "Cyber Investigator",
		"level.7": "Threat Analyst",
		"level.8": "Cyber Defender",
		"level.9": "Elite Defender",
		"level.10": "Cyber Sentinel",

		"streak.combo_prefix": "Combo",
		"streak.level_up_prefix": "LEVEL UP!",

		"debrief.score_base": "Base",
		"debrief.score_speed_bonus": "Speed Bonus",
		"debrief.score_streak_bonus": "Streak Bonus",

		"badge.perfect_run": "Perfect Run",
		"badge.speed_demon": "Speed Demon",
		"badge.cyber_sentinel": "Cyber Sentinel",

		"action.rapidfire.safe": "Safe",
		"action.rapidfire.unsafe": "Unsafe",
		"rapidfire.instruction": "Decide fast - SAFE or UNSAFE?",
		"rapidfire.timeout": "Time's up!",

		"action.vulnhunt.flag": "Flag as Vulnerability",
		"action.vulnhunt.ignore": "This Is Fine",

		"menu.cybersense": "CyberSense",
		"cybersense.title": "CyberSense",
		"cybersense.subtitle": "Paste a suspicious message and get an instant risk analysis.",
		"cybersense.placeholder": "Paste an email, message, or call transcript here...",
		"cybersense.analyze": "Analyze",
		"cybersense.risk_label": "Risk Level:",
		"cybersense.risk_low": "LOW RISK",
		"cybersense.risk_medium": "MEDIUM RISK",
		"cybersense.risk_high": "HIGH RISK",
		"cybersense.risk_critical": "CRITICAL RISK",
		"cybersense.indicators_title": "Indicators Found:",
		"cybersense.no_indicators": "No obvious red flags detected - but always stay cautious.",
		"cybersense.empty_input": "Paste some text first.",
		"cybersense.indicator_urgency": "Urgency language pressuring you to act fast",
		"cybersense.indicator_credential_request": "Requests a credential (OTP, PIN, password, or CVV)",
		"cybersense.indicator_suspicious_link": "Contains a suspicious or shortened link",
		"cybersense.indicator_generic_greeting": "Generic greeting instead of your real name",
		"cybersense.indicator_too_good": "Too-good-to-be-true prize or cashback offer",
		"cybersense.indicator_payment_pressure": "Pressures you to send or approve a payment",

		"start.subtitle": "Walk into any room in Cyber City to begin training.",
		"start.begin": "Start",

		"avatar.title": "Choose Your Avatar",
		"avatar.man": "Man",
		"avatar.woman": "Woman",
		"avatar.confirm": "Enter Cyber City",

		"hub.welcome": "Welcome to Cyber City",
		"hub.walk_hint": "Walk into a room to begin training.",
		"hub.menu_hint": "Esc to click",

		"instruction.title_prefix": "Training Briefing:",
		"instruction.continue": "Got It",
		"instruction.phishing_inbox": "Emails in your inbox may be real or fake. Open one to read it. Hover over the sender name or the link inside to reveal where they really lead, then Report, Delete, or Ignore based on what you find.",
		"instruction.upi_otp_kiosk": "You'll receive incoming payment and OTP requests under a countdown. Type an OTP and submit it, Approve a payment, or Decline - choose fast, but choose carefully.",
		"instruction.fake_login_corridor": "Each login page shows its address bar. Tap the address bar to zoom in and inspect the domain closely before deciding whether to flag it as suspicious, enter your credentials, or simply leave.",
		"instruction.password_vault_lab": "Type a password to secure this vault. You will not be told if it's weak or strong while typing - if it's too weak, someone will notice.",
		"instruction.safe_browsing_street": "Each storefront has a big tempting button and smaller, quieter controls. The big button is not always the right choice - check the certificate or leave if something feels off.",
		"instruction.rapid_fire": "Statements will come fast. Judge each one SAFE or UNSAFE before the timer runs out - speed and accuracy both count.",
		"instruction.vulnerability_hunt": "This office has several hidden weaknesses scattered around it. Explore and flag each real vulnerability you find - some objects are actually fine, so look carefully.",
		"instruction.cybersense": "Paste any suspicious message into the terminal and CyberSense will scan it for common red flags and estimate its risk level.",

		"rapidfire.officer_name": "Training Officer",

		"vault.alert_title": "INTRUSION DETECTED",
		"vault.alert_body": "That password was too weak - an attacker just broke in.",
		"vault.secured_title": "VAULT SECURED",
		"vault.secured_body": "Strong password - the vault holds.",
		"vault.attacker_label": "Attacker",
	},
	"hi": {
		"common.connection_error": "कनेक्शन त्रुटि, क्या सर्वर चल रहा है?",
		"common.continue": "जारी रखें",
		"common.back": "वापस",
		"common.cancel": "रद्द करें",
		"common.submit": "जमा करें",
		"common.loading": "लोड हो रहा है...",

		"menu.title": "साइबरगार्ड 3D",
		"menu.login": "लॉगिन",
		"menu.register": "रजिस्टर करें",
		"menu.leaderboard": "लीडरबोर्ड",
		"menu.quit": "बाहर निकलें",
		"menu.language": "भाषा",
		"menu.logout": "लॉग आउट",

		"login.title": "लॉगिन",
		"login.username": "उपयोगकर्ता नाम",
		"login.password": "पासवर्ड",
		"login.submit": "लॉगिन करें",
		"login.switch_to_register": "खाता नहीं है? रजिस्टर करें",
		"login.error_generic": "लॉगिन विफल।",

		"register.title": "रजिस्टर करें",
		"register.username": "उपयोगकर्ता नाम",
		"register.email": "ईमेल",
		"register.password": "पासवर्ड",
		"register.confirm_password": "पासवर्ड की पुष्टि करें",
		"register.submit": "रजिस्टर करें",
		"register.switch_to_login": "पहले से खाता है? लॉगिन करें",
		"register.error_password_mismatch": "पासवर्ड मेल नहीं खाते।",
		"register.error_empty_fields": "सभी फ़ील्ड आवश्यक हैं।",
		"register.error_invalid_email": "मान्य ईमेल पता दर्ज करें।",
		"register.success": "खाता बन गया! कृपया लॉगिन करें।",

		"hud.trust_score": "ट्रस्ट स्कोर",
		"hud.room_label": "कमरा",

		"rooms.phishing_inbox": "फ़िशिंग इनबॉक्स",
		"rooms.upi_otp_kiosk": "यूपीआई / ओटीपी कियोस्क",
		"rooms.fake_login_corridor": "नकली लॉगिन गलियारा",
		"rooms.password_vault_lab": "पासवर्ड वॉल्ट लैब",
		"rooms.safe_browsing_street": "सुरक्षित ब्राउज़िंग स्ट्रीट",
		"rooms.rapid_fire": "रैपिड फायर",
		"rooms.vulnerability_hunt": "वल्नरेबिलिटी हंट",
		"rooms.cybersense": "साइबरसेंस",

		"action.email.opened": "खोलें",
		"action.email.reported": "रिपोर्ट करें",
		"action.email.deleted": "हटाएं",
		"action.email.ignored": "अनदेखा करें",
		"action.payment.approve": "स्वीकृत करें",
		"action.payment.decline": "अस्वीकार करें",
		"action.payment.verify_first": "पहले सत्यापित करें",
		"action.login.enter_credentials": "क्रेडेंशियल दर्ज करें",
		"action.login.check_url": "यूआरएल जांचें",
		"action.login.leave_page": "पेज छोड़ें",
		"action.storefront.enter_site": "साइट में प्रवेश करें",
		"action.storefront.check_certificate": "प्रमाणपत्र जांचें",
		"action.storefront.leave": "छोड़ें",

		"password.title": "अपना पासवर्ड सेट करें",
		"password.placeholder": "एक पासवर्ड टाइप करें...",
		"password.strength_weak": "कमज़ोर",
		"password.strength_medium": "मध्यम",
		"password.strength_strong": "मज़बूत",
		"password.submit": "पासवर्ड जमा करें",

		"debrief.correct": "सही!",
		"debrief.incorrect": "यह एक गलती थी।",
		"debrief.trust_change": "ट्रस्ट स्कोर",
		"debrief.red_flags_title": "इससे पता चला:",
		"debrief.none_title": "यह सुरक्षित क्यों था:",
		"debrief.continue": "जारी रखें",

		"badge.toast_prefix": "बैज अर्जित:",
		"badge.phishing_inbox_expert": "फ़िशिंग विशेषज्ञ",
		"badge.upi_otp_kiosk_expert": "यूपीआई सुरक्षा विशेषज्ञ",
		"badge.fake_login_corridor_expert": "लॉगिन सतर्कता विशेषज्ञ",
		"badge.password_vault_lab_expert": "पासवर्ड प्रो",
		"badge.safe_browsing_street_expert": "सुरक्षित ब्राउज़िंग विशेषज्ञ",

		"leaderboard.title": "लीडरबोर्ड",
		"leaderboard.rank": "रैंक",
		"leaderboard.username": "खिलाड़ी",
		"leaderboard.trust_score": "ट्रस्ट स्कोर",
		"leaderboard.empty": "अभी तक कोई स्कोर नहीं। पहले बनें!",

		"admin.title": "साइबरगार्ड 3D - परिदृश्य व्यवस्थापक",
		"admin.add": "परिदृश्य जोड़ें",
		"admin.edit": "संपादित करें",
		"admin.delete": "हटाएं",
		"admin.save": "सहेजें",
		"admin.cancel": "रद्द करें",
		"admin.field.code": "कोड",
		"admin.field.room": "कमरा",
		"admin.field.title": "शीर्षक",
		"admin.field.difficulty": "कठिनाई",
		"admin.field.is_fraud": "क्या धोखाधड़ी है",
		"admin.field.red_flags": "चेतावनी संकेत",
		"admin.field.correct_actions": "सही कार्रवाई",
		"admin.no_auth_notice": "इस निर्माण चरण में कोई व्यवस्थापक प्रमाणीकरण नहीं है - README देखें।",
		"admin.field.content": "सामग्री (JSON)",

		"email.reader.tooltip_prefix": "असली पता: ",
		"email.reader.instruction": "ईमेल ध्यान से पढ़ें। प्रेषक या लिंक की जांच करने के लिए उस पर होवर करें।",

		"upi.otp_placeholder": "प्राप्त ओटीपी दर्ज करें",
		"upi.submit_otp": "ओटीपी जमा करें",
		"upi.incoming_request": "इनकमिंग रिक्वेस्ट",
		"upi.time_remaining": "शेष समय:",

		"login.zoom_domain": "एड्रेस बार जांचें",
		"login.flag_suspicious": "संदिग्ध के रूप में चिह्नित करें",
		"login.looks_legit": "वैध लगता है",
		"login.zoom_instruction": "निर्णय लेने से पहले एड्रेस बार को ध्यान से जांचने के लिए उस पर टैप करें।",

		"password.crack_time_label": "क्रैक होने में समय:",
		"password.crack_instant": "तुरंत",
		"password.crack_centuries": "सदियाँ",
		"password.crack_status_cracked": "क्रैक हो गया!",
		"password.crack_status_secure": "सुरक्षित",
		"password.unit_seconds": "सेकंड",
		"password.unit_minutes": "मिनट",
		"password.unit_hours": "घंटे",
		"password.unit_days": "दिन",
		"password.unit_years": "वर्ष",

		"storefront.claim_now": "अभी क्लेम करें!",
		"storefront.address_prefix": "पता: ",

		"level.1": "साइबर रूकी",
		"level.2": "डिजिटल स्काउट",
		"level.3": "थ्रेट स्पॉटर",
		"level.4": "साइबर ट्रेनी",
		"level.5": "सिक्योरिटी एजेंट",
		"level.6": "साइबर इन्वेस्टिगेटर",
		"level.7": "थ्रेट एनालिस्ट",
		"level.8": "साइबर डिफेंडर",
		"level.9": "एलीट डिफेंडर",
		"level.10": "साइबर सेंटिनल",

		"streak.combo_prefix": "कॉम्बो",
		"streak.level_up_prefix": "लेवल अप!",

		"debrief.score_base": "आधार",
		"debrief.score_speed_bonus": "स्पीड बोनस",
		"debrief.score_streak_bonus": "स्ट्रीक बोनस",

		"badge.perfect_run": "परफेक्ट रन",
		"badge.speed_demon": "स्पीड डेमन",
		"badge.cyber_sentinel": "साइबर सेंटिनल",

		"action.rapidfire.safe": "सुरक्षित",
		"action.rapidfire.unsafe": "असुरक्षित",
		"rapidfire.instruction": "जल्दी तय करें - सुरक्षित या असुरक्षित?",
		"rapidfire.timeout": "समय समाप्त!",

		"action.vulnhunt.flag": "कमजोरी के रूप में चिह्नित करें",
		"action.vulnhunt.ignore": "यह ठीक है",

		"menu.cybersense": "साइबरसेंस",
		"cybersense.title": "साइबरसेंस",
		"cybersense.subtitle": "एक संदिग्ध संदेश पेस्ट करें और तुरंत जोखिम विश्लेषण प्राप्त करें।",
		"cybersense.placeholder": "यहां एक ईमेल, संदेश, या कॉल ट्रांसक्रिप्ट पेस्ट करें...",
		"cybersense.analyze": "विश्लेषण करें",
		"cybersense.risk_label": "जोखिम स्तर:",
		"cybersense.risk_low": "कम जोखिम",
		"cybersense.risk_medium": "मध्यम जोखिम",
		"cybersense.risk_high": "उच्च जोखिम",
		"cybersense.risk_critical": "गंभीर जोखिम",
		"cybersense.indicators_title": "पाए गए संकेतक:",
		"cybersense.no_indicators": "कोई स्पष्ट चेतावनी संकेत नहीं मिला - फिर भी सतर्क रहें।",
		"cybersense.empty_input": "पहले कुछ टेक्स्ट पेस्ट करें।",
		"cybersense.indicator_urgency": "जल्दबाजी में कार्रवाई करने का दबाव डालने वाली भाषा",
		"cybersense.indicator_credential_request": "क्रेडेंशियल (OTP, PIN, पासवर्ड, या CVV) मांगता है",
		"cybersense.indicator_suspicious_link": "एक संदिग्ध या छोटा किया गया लिंक शामिल है",
		"cybersense.indicator_generic_greeting": "आपके असली नाम के बजाय सामान्य अभिवादन",
		"cybersense.indicator_too_good": "बहुत अच्छा लगने वाला इनाम या कैशबैक ऑफर",
		"cybersense.indicator_payment_pressure": "भुगतान भेजने या स्वीकृत करने का दबाव डालता है",

		"start.subtitle": "प्रशिक्षण शुरू करने के लिए साइबर सिटी में किसी भी कमरे में जाएं।",
		"start.begin": "शुरू करें",

		"avatar.title": "अपना अवतार चुनें",
		"avatar.man": "पुरुष",
		"avatar.woman": "महिला",
		"avatar.confirm": "साइबर सिटी में प्रवेश करें",

		"hub.welcome": "साइबर सिटी में आपका स्वागत है",
		"hub.walk_hint": "प्रशिक्षण शुरू करने के लिए किसी कमरे में चलें।",
		"hub.menu_hint": "क्लिक करने के लिए Esc दबाएं",

		"instruction.title_prefix": "प्रशिक्षण ब्रीफिंग:",
		"instruction.continue": "समझ गया",
		"instruction.phishing_inbox": "आपके इनबॉक्स में ईमेल असली या नकली हो सकते हैं। पढ़ने के लिए एक खोलें। प्रेषक नाम या अंदर के लिंक पर होवर करके देखें कि वे वास्तव में कहां जाते हैं, फिर जो पाएं उसके आधार पर रिपोर्ट करें, हटाएं, या अनदेखा करें।",
		"instruction.upi_otp_kiosk": "आपको काउंटडाउन के तहत भुगतान और ओटीपी अनुरोध प्राप्त होंगे। ओटीपी टाइप करके जमा करें, भुगतान स्वीकृत करें, या अस्वीकार करें - तेज़ी से चुनें, लेकिन सावधानी से चुनें।",
		"instruction.fake_login_corridor": "हर लॉगिन पेज अपना एड्रेस बार दिखाता है। निर्णय लेने से पहले डोमेन की बारीकी से जांच करने के लिए एड्रेस बार पर टैप करें, फिर तय करें कि इसे संदिग्ध चिह्नित करना है, क्रेडेंशियल दर्ज करना है, या बस छोड़ देना है।",
		"instruction.password_vault_lab": "इस वॉल्ट को सुरक्षित करने के लिए एक पासवर्ड टाइप करें। टाइप करते समय आपको नहीं बताया जाएगा कि यह कमज़ोर है या मज़बूत - अगर यह बहुत कमज़ोर है, तो किसी को पता चल जाएगा।",
		"instruction.safe_browsing_street": "हर दुकान में एक बड़ा लुभावना बटन और छोटे, शांत नियंत्रण होते हैं। बड़ा बटन हमेशा सही विकल्प नहीं होता - अगर कुछ गड़बड़ लगे तो प्रमाणपत्र जांचें या छोड़ दें।",
		"instruction.rapid_fire": "कथन तेज़ी से आएंगे। टाइमर समाप्त होने से पहले हर एक को सुरक्षित या असुरक्षित आंकें - गति और सटीकता दोनों मायने रखते हैं।",
		"instruction.vulnerability_hunt": "इस कार्यालय में कई छिपी हुई कमजोरियां बिखरी हुई हैं। खोजें और हर वास्तविक कमजोरी को चिह्नित करें - कुछ वस्तुएं वास्तव में ठीक हैं, इसलिए ध्यान से देखें।",
		"instruction.cybersense": "किसी भी संदिग्ध संदेश को टर्मिनल में पेस्ट करें और साइबरसेंस सामान्य चेतावनी संकेतों के लिए इसे स्कैन करेगा और इसके जोखिम स्तर का अनुमान लगाएगा।",

		"rapidfire.officer_name": "प्रशिक्षण अधिकारी",

		"vault.alert_title": "घुसपैठ का पता चला",
		"vault.alert_body": "वह पासवर्ड बहुत कमज़ोर था - एक हमलावर अभी अंदर घुस आया।",
		"vault.secured_title": "वॉल्ट सुरक्षित",
		"vault.secured_body": "मज़बूत पासवर्ड - वॉल्ट बचा रहा।",
		"vault.attacker_label": "हमलावर",
	},
	"mr": {
		"common.connection_error": "कनेक्शन त्रुटी, सर्व्हर सुरू आहे का?",
		"common.continue": "पुढे चला",
		"common.back": "मागे",
		"common.cancel": "रद्द करा",
		"common.submit": "सबमिट करा",
		"common.loading": "लोड होत आहे...",

		"menu.title": "सायबरगार्ड 3D",
		"menu.login": "लॉगिन",
		"menu.register": "नोंदणी करा",
		"menu.leaderboard": "लीडरबोर्ड",
		"menu.quit": "बाहेर पडा",
		"menu.language": "भाषा",
		"menu.logout": "लॉग आउट",

		"login.title": "लॉगिन",
		"login.username": "वापरकर्तानाव",
		"login.password": "पासवर्ड",
		"login.submit": "लॉगिन करा",
		"login.switch_to_register": "खाते नाही? नोंदणी करा",
		"login.error_generic": "लॉगिन अयशस्वी.",

		"register.title": "नोंदणी करा",
		"register.username": "वापरकर्तानाव",
		"register.email": "ईमेल",
		"register.password": "पासवर्ड",
		"register.confirm_password": "पासवर्डची पुष्टी करा",
		"register.submit": "नोंदणी करा",
		"register.switch_to_login": "आधीच खाते आहे? लॉगिन करा",
		"register.error_password_mismatch": "पासवर्ड जुळत नाहीत.",
		"register.error_empty_fields": "सर्व फील्ड आवश्यक आहेत.",
		"register.error_invalid_email": "वैध ईमेल पत्ता टाका.",
		"register.success": "खाते तयार झाले! कृपया लॉगिन करा.",

		"hud.trust_score": "ट्रस्ट स्कोअर",
		"hud.room_label": "खोली",

		"rooms.phishing_inbox": "फिशिंग इनबॉक्स",
		"rooms.upi_otp_kiosk": "यूपीआय / ओटीपी कियोस्क",
		"rooms.fake_login_corridor": "नकली लॉगिन कॉरिडॉर",
		"rooms.password_vault_lab": "पासवर्ड व्हॉल्ट लॅब",
		"rooms.safe_browsing_street": "सुरक्षित ब्राउझिंग स्ट्रीट",
		"rooms.rapid_fire": "रॅपिड फायर",
		"rooms.vulnerability_hunt": "व्हल्नरेबिलिटी हंट",
		"rooms.cybersense": "सायबरसेन्स",

		"action.email.opened": "उघडा",
		"action.email.reported": "तक्रार करा",
		"action.email.deleted": "काढून टाका",
		"action.email.ignored": "दुर्लक्ष करा",
		"action.payment.approve": "मंजूर करा",
		"action.payment.decline": "नाकारा",
		"action.payment.verify_first": "आधी पडताळणी करा",
		"action.login.enter_credentials": "क्रेडेन्शियल टाका",
		"action.login.check_url": "यूआरएल तपासा",
		"action.login.leave_page": "पेज सोडा",
		"action.storefront.enter_site": "साइटमध्ये प्रवेश करा",
		"action.storefront.check_certificate": "प्रमाणपत्र तपासा",
		"action.storefront.leave": "सोडा",

		"password.title": "तुमचा पासवर्ड सेट करा",
		"password.placeholder": "पासवर्ड टाइप करा...",
		"password.strength_weak": "कमकुवत",
		"password.strength_medium": "मध्यम",
		"password.strength_strong": "मजबूत",
		"password.submit": "पासवर्ड सबमिट करा",

		"debrief.correct": "बरोबर!",
		"debrief.incorrect": "ही एक चूक होती.",
		"debrief.trust_change": "ट्रस्ट स्कोअर",
		"debrief.red_flags_title": "यामुळे ते उघड झाले:",
		"debrief.none_title": "हे सुरक्षित का होते:",
		"debrief.continue": "पुढे चला",

		"badge.toast_prefix": "बॅज मिळाला:",
		"badge.phishing_inbox_expert": "फिशिंग तज्ञ",
		"badge.upi_otp_kiosk_expert": "यूपीआय सुरक्षा तज्ञ",
		"badge.fake_login_corridor_expert": "लॉगिन सतर्कता तज्ञ",
		"badge.password_vault_lab_expert": "पासवर्ड प्रो",
		"badge.safe_browsing_street_expert": "सुरक्षित ब्राउझिंग तज्ञ",

		"leaderboard.title": "लीडरबोर्ड",
		"leaderboard.rank": "क्रमांक",
		"leaderboard.username": "खेळाडू",
		"leaderboard.trust_score": "ट्रस्ट स्कोअर",
		"leaderboard.empty": "अजून कोणतेही गुण नाहीत. पहिले व्हा!",

		"admin.title": "सायबरगार्ड 3D - परिस्थिती प्रशासक",
		"admin.add": "परिस्थिती जोडा",
		"admin.edit": "संपादित करा",
		"admin.delete": "काढून टाका",
		"admin.save": "जतन करा",
		"admin.cancel": "रद्द करा",
		"admin.field.code": "कोड",
		"admin.field.room": "खोली",
		"admin.field.title": "शीर्षक",
		"admin.field.difficulty": "अडचण पातळी",
		"admin.field.is_fraud": "फसवणूक आहे का",
		"admin.field.red_flags": "इशारा चिन्हे",
		"admin.field.correct_actions": "योग्य कृती",
		"admin.no_auth_notice": "या निर्मिती टप्प्यात कोणतेही प्रशासक प्रमाणीकरण नाही - README पहा.",
		"admin.field.content": "मजकूर (JSON)",

		"email.reader.tooltip_prefix": "खरा पत्ता: ",
		"email.reader.instruction": "ईमेल काळजीपूर्वक वाचा. प्रेषक किंवा लिंक तपासण्यासाठी त्यावर होवर करा.",

		"upi.otp_placeholder": "मिळालेला ओटीपी टाका",
		"upi.submit_otp": "ओटीपी सबमिट करा",
		"upi.incoming_request": "येणारी विनंती",
		"upi.time_remaining": "उरलेला वेळ:",

		"login.zoom_domain": "अ‍ॅड्रेस बार तपासा",
		"login.flag_suspicious": "संशयास्पद म्हणून चिन्हांकित करा",
		"login.looks_legit": "खरे वाटते",
		"login.zoom_instruction": "निर्णय घेण्यापूर्वी अ‍ॅड्रेस बार बारकाईने तपासण्यासाठी त्यावर टॅप करा.",

		"password.crack_time_label": "क्रॅक होण्यासाठी लागणारा वेळ:",
		"password.crack_instant": "त्वरित",
		"password.crack_centuries": "शतके",
		"password.crack_status_cracked": "क्रॅक झाले!",
		"password.crack_status_secure": "सुरक्षित",
		"password.unit_seconds": "सेकंद",
		"password.unit_minutes": "मिनिटे",
		"password.unit_hours": "तास",
		"password.unit_days": "दिवस",
		"password.unit_years": "वर्षे",

		"storefront.claim_now": "आत्ताच क्लेम करा!",
		"storefront.address_prefix": "पत्ता: ",

		"level.1": "सायबर रूकी",
		"level.2": "डिजिटल स्काउट",
		"level.3": "थ्रेट स्पॉटर",
		"level.4": "सायबर ट्रेनी",
		"level.5": "सिक्युरिटी एजंट",
		"level.6": "सायबर इन्व्हेस्टिगेटर",
		"level.7": "थ्रेट अॅनालिस्ट",
		"level.8": "सायबर डिफेंडर",
		"level.9": "एलिट डिफेंडर",
		"level.10": "सायबर सेंटिनल",

		"streak.combo_prefix": "कॉम्बो",
		"streak.level_up_prefix": "लेव्हल अप!",

		"debrief.score_base": "आधार",
		"debrief.score_speed_bonus": "स्पीड बोनस",
		"debrief.score_streak_bonus": "स्ट्रीक बोनस",

		"badge.perfect_run": "परफेक्ट रन",
		"badge.speed_demon": "स्पीड डेमन",
		"badge.cyber_sentinel": "सायबर सेंटिनल",

		"action.rapidfire.safe": "सुरक्षित",
		"action.rapidfire.unsafe": "असुरक्षित",
		"rapidfire.instruction": "पटकन ठरवा - सुरक्षित की असुरक्षित?",
		"rapidfire.timeout": "वेळ संपली!",

		"action.vulnhunt.flag": "त्रुटी म्हणून चिन्हांकित करा",
		"action.vulnhunt.ignore": "हे ठीक आहे",

		"menu.cybersense": "सायबरसेन्स",
		"cybersense.title": "सायबरसेन्स",
		"cybersense.subtitle": "संशयास्पद संदेश पेस्ट करा आणि त्वरित जोखीम विश्लेषण मिळवा.",
		"cybersense.placeholder": "येथे ईमेल, संदेश किंवा कॉल ट्रान्सक्रिप्ट पेस्ट करा...",
		"cybersense.analyze": "विश्लेषण करा",
		"cybersense.risk_label": "जोखीम पातळी:",
		"cybersense.risk_low": "कमी जोखीम",
		"cybersense.risk_medium": "मध्यम जोखीम",
		"cybersense.risk_high": "उच्च जोखीम",
		"cybersense.risk_critical": "गंभीर जोखीम",
		"cybersense.indicators_title": "आढळलेले संकेत:",
		"cybersense.no_indicators": "कोणतीही स्पष्ट धोक्याची चिन्हे आढळली नाहीत - तरीही सावध रहा.",
		"cybersense.empty_input": "आधी काही मजकूर पेस्ट करा.",
		"cybersense.indicator_urgency": "पटकन कृती करण्यासाठी दबाव आणणारी भाषा",
		"cybersense.indicator_credential_request": "क्रेडेन्शियल (ओटीपी, पिन, पासवर्ड किंवा सीव्हीव्ही) मागते",
		"cybersense.indicator_suspicious_link": "संशयास्पद किंवा लहान केलेली लिंक आहे",
		"cybersense.indicator_generic_greeting": "तुमच्या खऱ्या नावाऐवजी सर्वसाधारण अभिवादन",
		"cybersense.indicator_too_good": "खूप चांगले वाटणारे बक्षीस किंवा कॅशबॅक ऑफर",
		"cybersense.indicator_payment_pressure": "पैसे पाठवण्यासाठी किंवा मंजूर करण्यासाठी दबाव आणते",

		"start.subtitle": "प्रशिक्षण सुरू करण्यासाठी सायबर सिटीमधील कोणत्याही खोलीत जा.",
		"start.begin": "सुरू करा",

		"avatar.title": "तुमचा अवतार निवडा",
		"avatar.man": "पुरुष",
		"avatar.woman": "स्त्री",
		"avatar.confirm": "सायबर सिटीमध्ये प्रवेश करा",

		"hub.welcome": "सायबर सिटीमध्ये आपले स्वागत आहे",
		"hub.walk_hint": "प्रशिक्षण सुरू करण्यासाठी एखाद्या खोलीत चाला.",
		"hub.menu_hint": "क्लिक करण्यासाठी Esc दाबा",

		"instruction.title_prefix": "प्रशिक्षण माहिती:",
		"instruction.continue": "समजले",
		"instruction.phishing_inbox": "तुमच्या इनबॉक्समधील ईमेल खरे किंवा खोटे असू शकतात. वाचण्यासाठी एक उघडा. प्रेषकाचे नाव किंवा आतील लिंकवर होवर करून ते खरोखर कुठे नेतात ते पहा, मग जे सापडेल त्यानुसार तक्रार करा, काढून टाका किंवा दुर्लक्ष करा.",
		"instruction.upi_otp_kiosk": "तुम्हाला काउंटडाउनखाली पेमेंट आणि ओटीपी विनंत्या येतील. ओटीपी टाइप करून सबमिट करा, पेमेंट मंजूर करा किंवा नाकारा - पटकन निवडा, पण काळजीपूर्वक निवडा.",
		"instruction.fake_login_corridor": "प्रत्येक लॉगिन पेज त्याचा अ‍ॅड्रेस बार दाखवते. निर्णय घेण्यापूर्वी डोमेन बारकाईने तपासण्यासाठी अ‍ॅड्रेस बारवर टॅप करा, मग ते संशयास्पद म्हणून चिन्हांकित करायचे, क्रेडेन्शियल टाकायचे, की फक्त सोडून द्यायचे ते ठरवा.",
		"instruction.password_vault_lab": "हा व्हॉल्ट सुरक्षित करण्यासाठी पासवर्ड टाइप करा. टाइप करताना तो कमकुवत आहे की मजबूत हे तुम्हाला सांगितले जाणार नाही - जर तो खूप कमकुवत असेल, तर कोणाला तरी ते लक्षात येईल.",
		"instruction.safe_browsing_street": "प्रत्येक दुकानात एक मोठे आकर्षक बटण आणि लहान, शांत नियंत्रणे असतात. मोठे बटण नेहमीच योग्य पर्याय नसते - काही चुकीचे वाटल्यास प्रमाणपत्र तपासा किंवा सोडून द्या.",
		"instruction.rapid_fire": "विधाने पटकन येतील. टायमर संपण्यापूर्वी प्रत्येकाला सुरक्षित किंवा असुरक्षित ठरवा - वेग आणि अचूकता दोन्ही महत्त्वाचे आहेत.",
		"instruction.vulnerability_hunt": "या ऑफिसमध्ये अनेक लपलेल्या त्रुटी विखुरलेल्या आहेत. शोध घ्या आणि सापडणाऱ्या प्रत्येक खऱ्या त्रुटीला चिन्हांकित करा - काही वस्तू खरोखर ठीक आहेत, म्हणून काळजीपूर्वक पहा.",
		"instruction.cybersense": "कोणताही संशयास्पद संदेश टर्मिनलमध्ये पेस्ट करा आणि सायबरसेन्स सामान्य धोक्याच्या चिन्हांसाठी तो तपासेल आणि त्याच्या जोखीम पातळीचा अंदाज लावेल.",

		"rapidfire.officer_name": "प्रशिक्षण अधिकारी",

		"vault.alert_title": "घुसखोरी आढळली",
		"vault.alert_body": "तो पासवर्ड खूप कमकुवत होता - एक हल्लेखोर आत्ताच आत घुसला.",
		"vault.secured_title": "व्हॉल्ट सुरक्षित",
		"vault.secured_body": "मजबूत पासवर्ड - व्हॉल्ट टिकला.",
		"vault.attacker_label": "हल्लेखोर",
	},
}


func set_language(code: String) -> void:
	if not _strings.has(code):
		code = "en"
	current_language = code
	language_changed.emit(code)


func get_string(key: String) -> String:
	var table: Dictionary = _strings.get(current_language, _strings["en"])
	if table.has(key):
		return table[key]
	return _strings["en"].get(key, key)


func available_languages() -> Array:
	return _strings.keys()
